* Advent of Code 2024
I am not a lisp programmer, rather a lisp learner. My plan is to solve
each of the puzzles myself (as far as possible), then review other
submissions and refactor my code accordingly (with credit to sources
of better solutions).
Many thanks to everyone sharing their code on github - much
appreciated!
* License
Advent of code solutions - my solutions, with code from others,
    created in common lisp.
    
    Copyright (C) 2020  Paul Jewell and original coders.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see [[https://www.gnu.org/licenses/]]


